### ISSUE TITLE
no api for username and password protected supermarket info

### ISSUE THREAD

**Issue by shaibrown5** [beyond-io/superx#24]
after a bit of digging I found that all supermarket info that is username and password protected uses cerberus FTP https://www.cerberusftp.com/

I have searched and searched but have not found any api for it and do I am not sure how to connect to the FTP so that i may retrieve the supermarket prices info. 

https://www.consumers.org.il/item/transparency_price

open to suggestions

**Comment by aryehlev** [comment]
have you been able to solve this issue?

**Comment by shaibrown5** [comment]
no

**Comment by shaibrown5** [comment]
no i havent, and I have tried different methods, but have not been able to solve this problem

**Comment by simzacks** [comment]
I suggest leaving this until later and dealing specifically with the supermarkets you can retrieve. It isn't difficult to do, but it isn't worth the effort at this stage

**Comment by aryehlev** [comment]
👍 so let’s close This issue for now🙏
