### ISSUE TITLE
updating database

### ISSUE THREAD

**Issue by shaibrown5** [beyond-io/superx#52]
the extractor scripts are almost done, what needs to be done now is to see how we can delete the relevant tables in the db everyday and place the new information inside of it

**Comment by BenHurCreations** [comment]
@shaibrown5 did you manage to solve this issue?

**Comment by shaibrown5** [comment]
Ive found the way to empty the tables, Im working now on making it faster and also automating the extraction process through github actions
If someone is good with git hub actions i would appreciate some help

**Comment by BenHurCreations** [comment]
Wrote a quick guide for you to use in Slack, let us know when you finish so we can close this issue. good luck!

**Comment by BenHurCreations** [comment]
How's it going? any advance / issues you want to share?

**Comment by shaibrown5** [comment]
I have sent in a pr with a workflow that runs the code at 9 am. Only problem is I cant find a way to update without delete.

**Comment by aryehlev** [comment]
👍
