### ISSUE TITLE
CI & Testing

### ISSUE THREAD

**Issue by BenHurCreations** [beyond-io/superx#54]
CI script is mostly ready, there is a first test for register function and need to add more tests for login and to the other functions as well

**Comment by BenHurCreations** [comment]
- @aryehlev PRed comprehensive login tests which are about to be merged
- I am working on home page testing
- There is a slight problem with CI I'm trying to resolve
- Next testing session is going to be for the extractors hopefully to start this weekend

**Comment by shlomoklein** [comment]
sounds good, what is the problem with the ci? or is this outdated?

**Comment by shlomoklein** [comment]
if you have the home page testing covered i should start working on testing the extractors

**Comment by aryehlev** [comment]
Ci works, in terms of testing-all login tests work,
If you r working on the home page tests I will start working on tests for the extractors

**Comment by shaibrown5** [comment]
@aryehlev have you started? id so can i join you?

**Comment by aryehlev** [comment]
@shaibrown5 , yes i have mainly been thinking conceptually how to test it, we can work on this together
