### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by BenHurCreations** [beyond-io/superx#56]
Some guidlines for the project documenation need to be written:
- User guide- how to run the project from scratch and use its features
- Contribution guidelines- what are the base rules for writing and adding code to the project
- Architecture guide- how the project works, which frameworks are used, classes hierarchy, and different files purpose
- Upgrade the readme file

**Comment by shaibrown5** [comment]
@BenHurCreations  documentation is the .readme file?

**Comment by BenHurCreations** [comment]
![image](https://user-images.githubusercontent.com/68295608/96347799-aa267b00-10ac-11eb-9292-77e1895b8fdc.png)

**Comment by BenHurCreations** [comment]
Those are the requirements as mentioned in the SOW

**Comment by BenHurCreations** [comment]
everything is written, closing
