### ISSUE TITLE
Choosing License

### ISSUE THREAD

**Issue by shaibrown5** [beyond-io/superx#59]
Ive been reading about the different licenses that are available, and need to brainstorm with all of oyou to choose the right one.
found this website that gives insight into the different licenses:
https://choosealicense.com/licenses/

I was thinking that we need a license that protects this code from private distributions (meaning that if someone distributes the code it will have to be open source). This is because we want people to be able to add to the project in order to help people save money.

another thing i think is important it the patent clause. - to have an express grant of the patents in use(or future patents) by the public - meaning that anyone can use the patents. this is debatable.

Let me know what you guys think

**Comment by shaibrown5** [comment]
do we want copyleft or permissive?
copyleft - anyone who uses this software has to be licensed copyleft as well, any code deriving from ours is  open source, and any code we use for the project has to be open sourc and copy left as well

persmissive - basically allow people to do what they want with our code, use it for their closed source software for example.

I was thinking strong copyleft (cant profit off our work, and has to use copyleft license) - as i think it is in our interest that our code and the use of it stays open source. I beleive that the only code that can derive from ours is a type of product comparison, and I believe this should be open source.

**Comment by shaibrown5** [comment]
we need to check if the libraries and packages we use have licenses that restrict us to use a certain license

**Comment by aryehlev** [comment]
👍 I’ll look into it, I think we should seek some advice in this matter
