### ISSUE TITLE
Editing the files to run under Pylint code rules

### ISSUE THREAD

**Issue by BenHurCreations** [beyond-io/superx#66]
- @aryehlev started working on it, please expand more about it

- plus- I started adding comments to the code- such as this one in superx/templates/products_table.html:

""

These comments help future contributors understand the code better and have easy life contributing

We should divide the code and everyone will focus on several scripts and add comments + Pylint guidelines

@aryehlev  please say more about pylint guidelines

**Comment by shlomoklein** [comment]
@BenHurCreations solved!

**Comment by aryehlev** [comment]
Done
