### ISSUE TITLE
Parse files into database

### ISSUE THREAD

**Issue by shaibrown5** [beyond-io/superx#9]
This issue refers to parsing the xml data into the sql DB.

after going over the xml files from different supermarkets, Im starting to think that we need to alter the script according tot eh different super markets as the xml files differ from one another

https://www.consumers.org.il/item/transparency_price

this is the relevant web page

**Comment by simzacks** [comment]
How much do they differ?
There are 2 ways of doing this.
1) Checking for multiple tags (One super uses ManufacturerName and the other uses ManufactureName): 
elif node.tag in ["ManufacturerName", "ManufactureName"]:

2) Changing the file before starting the parsing process:
Replace "<ManufactureName>" with "<ManufacturerName>"

My suggestion is either picking one super to start with, and making that the standard.

**Comment by shaibrown5** [comment]
first off the names of the attribute differ, for instance item code in one, and a different name in another.

apart from that some dont have the actual name of the product, only its itemID, and in different super markets the itemID differ. this causes a major problem as without the name, there isnt a way to know what the product is.

apart from this the actual build of the XML tree differs. In all cases i need to search under root, and the child that holds the data is always the last - so i know where to search, the problem is, each block attribute that holds the relevant info has different levels for different supers, and as i mentioned, different names for the different attributed of the product (name, id, price...)

I believe it is best to start with shufersal for now and in time develop the code to work for multiple supermarkets

**Comment by simzacks** [comment]
The primary key of the item is the itemID.
You can have a table for alternative product names/descriptions. 
You can either choose to use one or multiple.One way of doing it will be to say if the item name/description that you are reading in is longer than the one that is in there, use the longer one, on the assumption that a longer name is better.

**Comment by shaibrown5** [comment]
but form what i saw ItemID differes from supermarket to supermarket

**Comment by simzacks** [comment]
Can you give an example of an itemid that is different?

**Comment by shaibrown5** [comment]
I believe i was wrong, but ill check the item codes again

**Comment by simzacks** [comment]
ItemIDs come from the manufacturer. They're the barcode that you see on every product
There are 2 possibilities for the problem you are seeing.
1) Items that the supermarket assigns a fake item id, such as fruit and meat. In that case, there should be an obvious an easy way to know the difference.
2) A very similar product with a different manufacturer barcode. (maybe a different amount in the box, or a different flavor or some other minor difference)
